"""Initial migration with all models

Revision ID: 8982078211c8
Revises: 
Create Date: 2025-10-03 23:39:40.267472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def UUID():
    return sa.String(36)


revision: str = '8982078211c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affirmation_templates',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('anonymous_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('caring_gesture_count', sa.Integer(), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('partner_link_code', sa.String(), nullable=True),
    sa.Column('partner_id', UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_partner_link_code'), 'users', ['partner_link_code'], unique=True)
    op.create_table('affirmations',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_id', UUID(), nullable=True),
    sa.Column('sent_via', sa.String(length=50), nullable=False),
    sa.Column('recipient_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['affirmation_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caring_gestures',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('post_id', UUID(), nullable=False),
    sa.Column('gesture_type', sa.String(length=50), nullable=False),
    sa.Column('anonymous_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('post_id', UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('anonymous_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('post_id', UUID(), nullable=False),
    sa.Column('anonymous_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'anonymous_user_id', name='uq_post_user_like')
    )
    op.create_table('user_progress',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('user_id', UUID(), nullable=False),
    sa.Column('module_id', UUID(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module_progress')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('caring_gestures')
    op.drop_table('affirmations')
    op.drop_index(op.f('ix_users_partner_link_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('posts')
    op.drop_table('modules')
    op.drop_table('affirmation_templates')
    # ### end Alembic commands ###
